// src/pages/Mateus/Home/components/mobile/game/elevator/domain/homeElevator.constants.ts

export const HOME_ELEVATOR_FLOOR_COUNT = 9;
export const HOME_ELEVATOR_TOP_FLOOR = HOME_ELEVATOR_FLOOR_COUNT - 1;
export const HOME_ELEVATOR_CAPACITY = 4;

export const HOME_ELEVATOR_MOVE_SPEED_FLOORS_PER_SECOND = 1.55;
export const HOME_ELEVATOR_DOOR_TRANSITION_SECONDS = 0.36;
export const HOME_ELEVATOR_DOOR_HOLD_SECONDS = 0.82;
export const HOME_ELEVATOR_BASE_SPAWN_SECONDS = 3.2;
export const HOME_ELEVATOR_MAX_WAITING_PASSENGERS = 13;
export const HOME_ELEVATOR_MIN_PATIENCE_SECONDS = 16;
export const HOME_ELEVATOR_MAX_PATIENCE_SECONDS = 28;

export const HOME_ELEVATOR_INITIAL_ENERGY = 100;
export const HOME_ELEVATOR_MOVE_ENERGY_PER_SECOND = 1.35;
export const HOME_ELEVATOR_DOOR_ENERGY = 1.2;
export const HOME_ELEVATOR_IDLE_RECOVERY_PER_SECOND = 0.5;
export const HOME_ELEVATOR_DELIVERY_SCORE = 120;
export const HOME_ELEVATOR_STREAK_BONUS = 18;
export const HOME_ELEVATOR_MISSED_PENALTY = 55;
