export const FREE_DRIVE_WORLD_SIZE_METERS = 1000;
export const FREE_DRIVE_WORLD_HALF_SIZE_METERS =
  FREE_DRIVE_WORLD_SIZE_METERS / 2;

export const FREE_DRIVE_START_POSITION_X = 0;
export const FREE_DRIVE_START_POSITION_Z = 0;
export const FREE_DRIVE_START_HEADING_RAD = 0;

export const FREE_DRIVE_WHEEL_BASE_METERS = 2.72;
export const FREE_DRIVE_START_SPEED_MPS = 8.2;
export const FREE_DRIVE_CRUISE_SPEED_MPS = 12.8;
export const FREE_DRIVE_MAX_SPEED_MPS = 17.8;
export const FREE_DRIVE_ACCELERATION_MPS2 = 5.8;
export const FREE_DRIVE_BRAKE_MPS2 = 12.5;
export const FREE_DRIVE_NATURAL_DRAG_MPS2 = 1.35;
export const FREE_DRIVE_STEER_SMOOTHING = 9.5;
export const FREE_DRIVE_MAX_STEER_ANGLE_DEG = 37;

export const FREE_DRIVE_WHEEL_VISUAL_MAX_ROTATION_DEG = 118;
export const FREE_DRIVE_LOOP_MAX_DELTA_SECONDS = 1 / 24;

export const FREE_DRIVE_TERRAIN_CELL_SIZE_METERS = 52;
export const FREE_DRIVE_TERRAIN_OBJECT_RADIUS_METERS = 430;
export const FREE_DRIVE_TERRAIN_TILE_SIZE_METERS = 100;

export const FREE_DRIVE_CAMERA_NEAR_METERS = 3.5;
export const FREE_DRIVE_CAMERA_FAR_METERS = 390;
export const FREE_DRIVE_CAMERA_HEIGHT_METERS = 1.38;
export const FREE_DRIVE_CAMERA_FOV_STRENGTH = 0.92;

export const FREE_DRIVE_STEERING_WHEEL_IMAGE_SRC =
  "/images/home-drive/free-drive-steering-wheel.png";
